DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS like;

CREATE TABLE user (
  uid TEXT PRIMARY KEY UNIQUE NOT NULL,
  displayName TEXT NOT NULL,
  type TEXT NOT NULL,
  accessLevel INTEGER NOT NULL, -- 0 none, 1 read only, 2 can post, 3 social media manager, 4 admin
  klasse TEXT DEFAULT NULL,
  profilePicFilename TEXT DEFAULT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT NULL,
  title TEXT NOT NULL,
  description TEXT,
  tags TEXT,
  publiched BIT NOT NULL DEFAULT 0, -- 0 NOT published on social media, 1 published on social media
  FOREIGN KEY (user_id) REFERENCES user (uid) ON DELETE CASCADE
);

CREATE TABLE like (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user (uid) ON DELETE CASCADE
);

CREATE TABLE comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  text TEXT NOT NULL,
  FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user (uid) ON DELETE CASCADE
);

CREATE TABLE media (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id INTEGER NOT NULL,
  mime_type TEXT NOT NULL,
  filename TEXT NOT NULL,
  FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE
);
